server:
  port: 9000

spring:
  profiles:
    active: dev

  # 数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #驱动
    username: root
    password: 1
    url: jdbc:mysql://localhost:3306/mp?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    schema: classpath:db/schema-mp.sql # 数据库 Schema(结构) 脚本
    data: classpath:db/data-mp.sql # 数据库 Data 脚本



# mybatis-plus相关配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 配置日志
    global-config:
      db-config:
        # logic-delete-field: deleted  # 全局逻辑删除的实体字段名（实体中删除标志属性名）(since 3.3.0,配置后可以忽略不配置步骤2) 注：如果想保留物理删除，就配置此项
        logic-delete-value: 1 # 逻辑已删除值(默认为 1)
        logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

